#!/usr/bin/env bash -e

dir_name="$(realpath "$PWD")"
repo_name="$(basename "$dir_name")"

: ${PROJECT="$(basename "$dir_name")"}

: ${TAG:="build"}
: ${IMAGE:="${namespace}$repo_name:${TAG}"}

exec docker build -t "$repo_name" .
