version: '2'
services:
  app:
    image: trevorj/docker-build-proxy
    build:
      context: .
      args:
        - http_proxy
        - https_proxy
    volumes:
      - .:/app
    ports:
      - "3142:3142"
      - "3480:3480"
      - "3443:3443"
    restart: always

