version: '2'
services:
  app:
    image: trevorj/docker-build-proxy
    build:
      context: .
      args:
        - http_proxy
        - https_proxy
    ports:
      - "3142:3142"
    restart: always

