#!/bin/bash
set -eo pipefail
[[ -z "$DEBUG" ]] || set -xv

logs=("$LOG_DIR/access.log" "$LOG_DIR/cache.log" "$LOG_DIR/store.log")

if [[ "$LOG_FIFO" == "true" ]]; then
    for log in "${logs[@]}"; do
        echo "[$0] Creating log fifo: $log"
        rm -f "$log"
        mkfifo "$log"
        chown proxy:proxy "$log"
    done
fi

CONFIG_TMPL_MARK="$CONFIG_DIR/.squid.conf-templated"
if [[ ! -f "$CONFIG_DIR/squid.conf" || -f "$CONFIG_TMPL_MARK" ]]; then
    echo "[$0] Templating squid.conf"
    touch "$CONFIG_TMPL_MARK"
    dockerize \
        -template "$APP_ROOT/squid.conf.tmpl":"$CONFIG_DIR/squid.conf"
fi

if [[ "$1" = squid* ]]; then
    set -- dockerize \
        $(for log in "${logs[@]}"; do echo -e " -stdout \"$log\" "; done) \
        "$@"
fi

if [[ -n "$SSL_BUMP_PORT" ]]; then
    generate-cert
fi

if [[ -n "$TRANSPARENT_PORT" ]]; then
    echo "[$0] Setting up transparent proxy DNAT in iptables"
    # Setup the NAT rule that enables transparent proxying
    IPADDR=$(/sbin/ip -o -f inet addr show eth0 | awk '{ sub(/\/.+/,"",$4); print $4 }')
    iptables -t nat -A PREROUTING -p tcp --dport 80 -j DNAT --to-destination "${IPADDR}:${TRANSPARENT_PORT}"
fi

echo "exec:" "$@"
exec "$@"
